spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/betcalculator?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      use-new-id-generator-mappings: false
    show-sql: false
  application:
    name: bet-calculator
    
#Swagger path 
springfox.documentation.swagger.v2.path: /${spring.application.name}/api-docs
    
    
logging:
  level:
    it.betcalculator: DEBUG
    


